# Theme Parameters
colorScheme = "ocean"
defaultAppearance = "dark"
autoSwitchAppearance = true

enableSearch = true
enableCodeCopy = true

mainSections = ["projects", "blog"]

# Background effects
defaultBackgroundImage = "/img/background.svg"

highlightCurrentMenuArea = true
smartTOC = true

[header]
  layout = "fixed-fill-blur"

[footer]
  showMenu = true
  showCopyright = true
  showThemeAttribution = false
  showAppearanceSwitcher = true
  showScrollToTop = true

[homepage]
  layout = "profile"
  showRecent = true
  showRecentItems = 6
  showMoreLink = true
  showMoreLinkDest = "projects"
  cardView = true
  cardViewScreenWidth = false
  layoutBackgroundBlur = true

[article]
  showDate = true
  showDateUpdated = false
  showAuthor = true
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  showBreadcrumbs = true 
  showDraftLabel = true
  showEdit = false
  showHeadingAnchors = true
  showPagination = true
  showReadingTime = true
  showTableOfContents = true
  showRelatedContent = false
  relatedContentLimit = 3
  showTaxonomies = true
  showWordCount = false
  sharingLinks = ["linkedin", "twitter", "email"]
  showZenMode = true

[list]
  showHero = true
  heroStyle = "background"
  layoutBackgroundBlur = true
  showBreadcrumbs = false
  showSummary = true
  showTableOfContents = false
  showCards = true
  cardView = true
  cardViewScreenWidth = false
  groupByYear = false

[taxonomy]
  showTermCount = true
  showHero = true
  heroStyle = "background"
  cardView = true

[term]
  showHero = true
  heroStyle = "background"
  cardView = true
